# For dev/test.
version: "2.2"
services:
  redis:
    image: redis:4-alpine
    command: redis-server --appendonly yes
  hub:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Override bundle flags so that development/test dependencies are installed.
        - BUNDLE_INSTALL_FLAGS=--jobs 5
        - SOURCE_COMMIT_SHA
    depends_on:
      - redis
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - REDIS_PASSWORD
      - HUB_REDIS_URL=redis://redis:6379
      - REDIS_SSL_CERTIFICATE_AUTHORITY_PATH
      - REDIS_SSL_CLIENT_CERTIFICATE_PATH
      - REDIS_SSL_PRIVATE_KEY_PATH
      - SENTRY_DSN
      - PERCY_ENV
    volumes:
      - .:/app/src
