steps:
  - name: ":rspec: RSpec"
    commands:
      - "make down"
      - "make build"
      - "make up-detached"
      - "make test"
      - "make down"

  - label: ":sunglasses: Style"
    commands:
      - "make down"
      - "make build"
      - "make up-detached"
      - "make rubocop"
      - "make down"
    artifact_paths: ./tmp/rubocop/*
    timeout_in_minutes: 10

  - wait: ~
    continue_on_failure: true

  - label: ":white_check_mark: Test Summary"
    plugins:
      - bugcrowd/test-summary#v1.9.1:
          inputs:
            - label: rubocop
              artifact_path: tmp/rubocop/*
              type: oneline
          formatter:
            type: details
          context: test-summary

  - name: ":docker: publish images"
    branches: "master"
    command: "make publish"

  - wait

  - label: ":percy::kubernetes::rocket: Deploy"
    trigger: "deploy-hub"
    branches: "master"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        TAG: "${BUILDKITE_COMMIT}"
